name: vuepress

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.SSH }}
      - uses: actions/checkout@v2
      - name: Build
        run: |
          yarn
          yarn docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          DEPLOY_KEY: ${{ secrets.SSH }}
          PUBLISH_DIR: docs/.vuepress/dist