name: vuepress

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取
          uses: actions/checkout@v2
      - name: 构建
        run: |
          yarn
          yarn docs:build
      - name: 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: docs/.vuepress/dist
          CNAME: www.fourteen.top
